export const TABLES = {
  profiles: "profiles",
  usernames: "usernames",
  friendRequests: "friend_requests",
  friendships: "friendships",
  blocks: "blocks",
  dmThreads: "dm_threads",
  dmMessages: "dm_messages",
  dmReads: "dm_reads",
  roomThreads: "room_threads",
  roomGroups: "room_groups",
  roomThreadGroups: "room_thread_groups",
  roomGroupMemberships: "room_group_memberships",
  roomThreadSubscriptions: "room_thread_subscriptions",
  roomMessages: "room_messages",
  roomReplies: "room_replies",
  roomReplyVotes: "room_reply_votes",
  roomMessageVotes: "room_message_votes",
} as const;

export const COLUMNS = {
  profiles: {
    id: "id",
    username: "username",
    role: "role",
    settings: "settings",
    avatarPath: "avatar_path",
  },
  usernames: {
    username: "username",
    userId: "uid",
  },
  friendRequests: {
    fromUser: "from_id",
    toUser: "to_id",
    createdAt: "created_at",
  },
  friendships: {
    userId: "user_a",
    friendId: "user_b",
    createdAt: "created_at",
  },
  blocks: {
    blockerId: "blocker_id",
    blockedId: "blocked_id",
    createdAt: "created_at",
  },
  dmThreads: {
    id: "id",
    userIds: "users",
    lastMessage: "last_message",
    lastTimestamp: "last_timestamp",
    hiddenBy: "hidden_by",
  },
  dmMessages: {
    id: "id",
    threadId: "thread_id",
    senderId: "sender",
    username: "username",
    text: "text",
    createdAt: "timestamp",
    attachmentPath: "attachment_path",
    attachmentName: "attachment_name",
    attachmentMime: "attachment_mime",
    attachmentSize: "attachment_size",
  },
  dmReads: {
    threadId: "thread_id",
    userId: "user_id",
    lastReadAt: "last_read_at",
  },
  roomThreads: {
    threadKey: "thread_key",
    threadNumber: "thread_number",
    title: "title",
    subtitle: "subtitle",
    isActive: "is_active",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  roomGroups: {
    groupKey: "group_key",
    name: "name",
    description: "description",
    createdAt: "created_at",
  },
  roomThreadGroups: {
    threadKey: "thread_key",
    groupKey: "group_key",
    createdAt: "created_at",
  },
  roomGroupMemberships: {
    userId: "user_id",
    groupKey: "group_key",
    createdAt: "created_at",
  },
  roomThreadSubscriptions: {
    userId: "user_id",
    threadKey: "thread_key",
    createdAt: "created_at",
  },
  roomMessages: {
    id: "id",
    roomKey: "room",
    senderId: "sender",
    username: "username",
    text: "text",
    createdAt: "timestamp",
    attachmentPath: "attachment_path",
    attachmentName: "attachment_name",
    attachmentMime: "attachment_mime",
    attachmentSize: "attachment_size",
  },
  roomReplies: {
    id: "id",
    roomMessageId: "message_id",
    senderId: "sender",
    username: "username",
    text: "text",
    createdAt: "timestamp",
    attachmentPath: "attachment_path",
    attachmentName: "attachment_name",
    attachmentMime: "attachment_mime",
    attachmentSize: "attachment_size",
  },
  roomReplyVotes: {
    replyId: "reply_id",
    userId: "user_id",
    value: "value",
  },
  roomMessageVotes: {
    messageId: "message_id",
    userId: "user_id",
    value: "value",
  },
} as const;
